version: 2
jobs:
    build_and_test_jdk8:
        working_directory: ~/MineProtocol-JDK8
        docker:
            - image: circleci/openjdk:8-jdk
        environment:
            MAVEN_OPTS: -Xmx2048m
        steps:
            - checkout
            - restore_cache:
                keys:
                - MineProtocol-{{ checksum "pom.xml" }}
                - MineProtocol-
            - run: mvn -B package
            - save_cache:
                paths:
                    - ~/.m2
                key: MineProtocol-{{ checksum "pom.xml" }}
            - store_test_results:
                path: target/surefire-reports
            - store_artifacts:
                path: target/*.jar
    build_and_test_jdk9:
        working_directory: ~/MineProtocol-JDK9
        docker:
            - image: circleci/openjdk:9-jdk
        environment:
            MAVEN_OPTS: -Xmx2048m
        steps:
            - checkout
            - restore_cache:
                keys:
                - MineProtocol-{{ checksum "pom.xml" }}
                - MineProtocol-
            - run: mvn -B package
            - save_cache:
                paths:
                    - ~/.m2
                key: MineProtocol-{{ checksum "pom.xml" }}
            - store_test_results:
                path: target/surefire-reports
            - store_artifacts:
                path: target/*.jar
    build_and_test_jdk10:
        working_directory: ~/MineProtocol-JDK10
        docker:
            - image: circleci/openjdk:10-jdk
        environment:
            MAVEN_OPTS: -Xmx2048m
        steps:
            - checkout
            - restore_cache:
                keys:
                - MineProtocol-{{ checksum "pom.xml" }}
                - MineProtocol-
            - run: mvn -B package
            - save_cache:
                paths:
                    - ~/.m2
                key: MineProtocol-{{ checksum "pom.xml" }}
            - store_test_results:
                path: target/surefire-reports
            - store_artifacts:
                path: target/*.jar
workflows:
    version: 2
    build_and_test:
        jobs:
            - build_and_test_jdk8
            - build_and_test_jdk9
            - build_and_test_jdk10
